default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: session_history
  password:

development:
  <<: *default
  database: session_history_development

test:
  <<: *default
  database: session_history_test

production:
  <<: *default
  database: session_history_production
